server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jdanielvalri/BC35_Proyecto_final.git
          searchPaths: Config-Data
          username: jdanielvalri
          password: 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

  security:
    user:
      name: root
      password: s3cr3t